# -*- coding: utf-8 -*-
"""analyst_copilot_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HL0Et9n7quV-BHnMEyhD93nmbE1gBFD6
"""

# --- Connect to Google Drive to access our dataset ---
from google.colab import drive
drive.mount('/content/drive')

# --- Install all the required libraries for our project ---
# The -q flag makes the installation "quiet" (less text output)
# The -U flag ensures we get the latest versions of the libraries
!pip install -q -U transformers datasets peft bitsandbytes accelerate trl torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0

# --- Step 3.1: Import all necessary libraries ---
import torch
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig
from trl import SFTTrainer
# NEW: Import for Hugging Face Login and Colab Secrets
from huggingface_hub import login
from google.colab import userdata

# --- Step 3.1a: Securely Log In to Hugging Face ---
# This is the new section that uses your secret token
print("--- Logging in to Hugging Face ---")
try:
    HF_TOKEN = userdata.get('HF_TOKEN')
    login(token=HF_TOKEN)
    print("--- Login Successful ---")
except Exception as e:
    print(e)
    print("--- Login Failed. Make sure you have stored your HF_TOKEN in Colab Secrets (key icon on the left). ---")


# --- Step 3.2: Load and Prepare Your Custom Dataset ---
print("--- Loading and Preparing Dataset ---")
# IMPORTANT: Make sure this path is correct for your Google Drive!
file_path = '/content/drive/MyDrive/Analyst/data/analyst_dataset.jsonl'
df = pd.read_json(path_or_buf=file_path, lines=True)
hg_dataset = Dataset.from_pandas(df)

# This function creates the specific prompt format the Gemma model expects
def format_prompt(example):
    return {"text": f"<start_of_turn>user\n{example['instruction']}\n\n{example['context']}<end_of_turn>\n<start_of_turn>model\n{example['answer']}<end_of_turn>"}

formatted_dataset = hg_dataset.map(format_prompt)
final_dataset = formatted_dataset.train_test_split(test_size=0.1)
print("--- Dataset is Ready ---")

# --- Step 3.3: Configure QLoRA and Load the Base Model ---
print("--- Configuring QLoRA and Loading Model ---")
# This is the QLoRA configuration that shrinks the model to 4-bits
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

# This is the specific open-source model we are specializing
model_id = "google/gemma-2b-it"

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
if tokenizer.pad_token is None:
    # Many models don't have a padding token, so we have to add one
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto", # This automatically uses our Colab GPU
    trust_remote_code=True
)

# This is the configuration for our LoRA "sticky notes"
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"]
)
print("--- Model and LoRA Config are Ready ---")

# --- Step 3.4: Set up Training and Run the Fine-Tuning Process ---
# Define where to save our final model adapter
output_dir = "/content/drive/MyDrive/Analyst/analyst_copilot_v1"

# Define the training arguments (without max_seq_length)
training_args = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    num_train_epochs=1,
    logging_steps=5,
    save_strategy="epoch",
    report_to="none",
)
# Create the Trainer object
trainer = SFTTrainer(
    model=model,
    train_dataset=final_dataset['train'],
    peft_config=lora_config,
    args=training_args,
    # Both dataset_text_field and max_seq_length have now been removed
)
print("--- Starting the Fine-Tuning Process ---")
# This one command starts the entire training job!
trainer.train()

# --- Step 3.5: Save the Final Trained Adapter ---
final_adapter_path = f"{output_dir}/final_adapter"
trainer.save_model(final_adapter_path)
print(f"--- SUCCESS! Phase 2 is complete. Your fine-tuned model adapter is saved to: {final_adapter_path} ---")



# --- Step 1: Install Libraries and Log In ---
# (This may already be done if you're in the same session)
!pip install -q -U transformers datasets peft bitsandbytes torch accelerate
from huggingface_hub import login
from google.colab import userdata
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel

# Log in to Hugging Face to get the base model
try:
    HF_TOKEN = userdata.get('HF_TOKEN')
    login(token=HF_TOKEN)
except Exception as e:
    print(e)
    print("Login Failed. Make sure HF_TOKEN is stored in Colab Secrets.")

# --- Step 2: Load the Base Model and Tokenizer ---
print("--- Loading Base Model (Gemma-2B-IT) ---")
model_id = "google/gemma-2b-it"

# Use the same 4-bit configuration as during training
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)
print("--- Base Model Loaded ---")


# --- Step 3: Load Your Fine-Tuned Adapter ---
# This is where we load the "brain" you trained
print("--- Loading Your Fine-Tuned Adapter ---")
adapter_path = "/content/drive/MyDrive/Analyst/analyst_copilot_v1/final_adapter"
model = PeftModel.from_pretrained(base_model, adapter_path)
print("--- Adapter Loaded Successfully ---")


# --- Step 4: Prepare and Run Your Test Prompt ---
print("\n--- Asking our new AI its first question... ---")
# Let's test it on the competitor identification task
test_instruction = "Based on the provided text describing the company's competitive landscape, list its main competitors."
# This is the same context we used in our dataset
test_context = """
Competitors to Office include software and global application vendors, such as Apple, Cisco Systems, Google, Meta, Proofpoint, Slack, Symantec, Zoom... Dynamics competes with cloud-based and on-premises business solution providers such as Oracle, Salesforce, SAP, Service Now, UI Path, and WorkDay. Azure faces diverse competition from companies such as Amazon, Broadcom, Google, IBM, Oracle, and open source offerings...
"""

# Format the prompt using the exact same template we used for training
prompt = f"<start_of_turn>user\n{test_instruction}\n\n{test_context}<end_of_turn>\n<start_of_turn>model\n"

# --- Step 5: Generate and Print the Answer ---
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

with torch.no_grad():
    outputs = model.generate(**inputs, max_new_tokens=256, temperature=0.1)

# Decode the output
response_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

# The model will output the full prompt, so we split to get just the answer
# This finds where the model's answer starts and prints only that part
answer_start = response_text.find("<start_of_turn>model\n")
final_answer = response_text[answer_start + len("<start_of_turn>model\n"):]


print("\n✅ AI Co-pilot's Answer:")
print(final_answer)

!nvidia-smi